### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by Looodon** [ANSH3LL/TinyFeed#2]
Hello, 

Just found out about your project and I'm so happy. I wanted to know what the privacy policy is if that's okay. Like what kind of data is collected and who receives it. Your project is solving a problem for many people so I have high hopes for its future!

Thank you!

**Comment by Looodon** [comment]
All I want to know is what data (if any) the software collects, thanks!

**Comment by ANSH3LL** [comment]
No data is collected.
All data the software generates is stored on the user's device and not sent anywhere.
Sorry for the late response.
